### ISSUE TITLE
Guide for using JDBCX with PRQL in DBeaver

### ISSUE THREAD

**Issue by swt30** [jdbcx/jdbcx#3]
FYI I wrote a slightly more comprehensive guide on how to set up JDBCX to run PRQL queries in DBeaver, by using DBeaver's integrated download functionality to get the relevant drivers from Maven: https://github.com/PRQL/prql/issues/1643#issuecomment-1651669452

Feel free to use this in your README or link to the comment :)

**Comment by zhicwu** [comment]
Thank you @swt30, that's very kind :) And apologize for the tedious work to get it working, as it's supposed to be very easy. Perhaps it's better to add the driver into DBeaver, so that nobody has to repeat most of the steps.

Lastly, I want to mention that some of the options are changed in the upcoming next release for consistency, for example: `jdbcx.prql.compile.error` is now `jdbcx.prql.exec.error`. Anyway, I'll close this after updating README. Thanks again!

**Comment by zhicwu** [comment]
Close as JDBCX driver has been added into DBeaver via dbeaver/dbeaver#20811
